### ISSUE TITLE
Psgs broke everything?

### ISSUE THREAD

**Issue by Carlgo11** [Carlgo11/UploadMe#4]
While we all love our beloved CSS oracle even oracles makes mistakes (not really) and we have to accept that.
We can't show a non-working site to the users tho so right now I've reverted @psgs' last night code cracking and instead pulled them to the branch `psgs-breaks-everything`. I also noticed our beloved CSS oracle made his own branch so I guess we have 2 now :P

Also:
#### All hail our savior @psgs and may he bless us with his CSS magic!
<i>I think I just created a new religion lol :smile:</i>

**Comment by psgs** [comment]
Hello @Carlgo11,

I tested all code locally before pushing it to GitHub, and pushed to ```css-changes``` before merging the code with the master branch.
Do you know what exactly was wrong with the code?

Thankyou,
psgs :palm_tree:

**Comment by Carlgo11** [comment]
Hi Psgs,

A few things like:
1. All directory links use / instead of ./ which breaks things locally
2. Navbar is put outside of class="container" which makes it look weird
3. Divs giving the user links and codes cover the entire page instead of keeping themselves inside the container.
4. All text is inside <center> which makes the privacy page look weird  

<i>and I like how you didn't even mention that I've founded a new religion around you :wink:</i>

**Comment by psgs** [comment]
Hello grand holy master @Carlgo11,

When testing locally with directory links, using the ```./``` path broke things for me. When the ```.``` was removed, the paths seemed to work.
The navbar, when placed outside ```class="container"``` (intentionally) also looked fine locally, and when you pushed changes to ```uploadme.carlgo11.com```.
I also couldn't observe links and codes covering the entire page.
In the later commits I pushed, notable commit ca2c6d80734535e1944207a8ddc7f1857a54c95d, all ```<center>``` tags were removed and replaced with styling found in ```stylesheet.css```.

Thankyou,
psgs :palm_tree:

**Comment by Carlgo11** [comment]
Well it seems like your local web server and my server's web server do entirly different things. I'll put up a second site on the server so that you can see

**Comment by Carlgo11** [comment]
Okay here's the site but with your css-changes branch: http://delta.carlgo11.com/UploadMe/
I've set it up so it automatically pulls new changes.

**Comment by psgs** [comment]
Hi @Carlgo11,

Unfortunately, the delta web-server doesn't seem to be loading any external CSS files or recognising files other than the UploadMe index page.
Perhaps this is an issue with the way in which website files are pulled from GitHub?

Thankyou,
psgs

**Comment by Carlgo11** [comment]
No it doesn't recognize any other files since you changed the ./ to / 😋

**Comment by psgs** [comment]
Oh, I think I see @Carlgo11 :smiley: 

Although changing ```/``` to ```./``` will allow the website to work on ```uploadme.carlgo11.com```, when the GitHub repository is cloned, the paths won't always link to the correct resources, due to the fact that the root folder of the GitHub repository points to the root folder of the website, however, this is not the case on the web-server.

I will push changes to the ```css-changes``` and ```psgs-breaks-everything``` branches, and try to eventually get the site working again on master.

Thanks,
psgs

**Comment by psgs** [comment]
@Carlgo11,

```delta.carlgo11.com/UploadMe``` doesn't seem to pull updates from the ```css-changes``` branch of UploadMe.

**Comment by Carlgo11** [comment]
Maybe you broke it then? #psgs-breaks-everything

I'll look at it when I get on my pc tomorrow. It seems like my private key for the phone doesn't work with delta

**Comment by Carlgo11** [comment]
okay I may or may not have forgotten to change the permissions for `delta.carlgo11.com/UploadMe` :neutral_face:

**Comment by psgs** [comment]
@Carlgo11,
Everything seems to look normal now that the file paths have been fixed.
Thankyou for going to the trouble of setting up a secondary web-server and troubleshooting this!

**Comment by Carlgo11** [comment]
Gosh @psgs! You've supriced me again! The site looks amazing! :smile: 
Just a few things I want to know about.
1. The picture of the creepy lady with the photo editing program looks really good but do we have permission to use that picture?
2. The centering on privacy.php looks kinda awful to be honest. Maybe you could somehow in your css godish ways remove that for just that page?
3. OMG OMG OMG! SUCH A WOW PAGE! :smiley: :tada:

**Comment by psgs** [comment]
Hello @Carlgo11,

All the images I have added were sourced from royalty free websites which
allow photos to be used both for personal and commercial use.

Thankyou,
psgs

**Comment by Carlgo11** [comment]
Splendid!
It seems like the server had some merge errors and so I fixed those now.
When testing the new site I noticed that the download link on done.php isn't centered for some reason.  
./lib/request-password.php also doesn't look proper as well.  

Once again, super awesome looking site you've made! :smiley:
